/**
 * Store nonce route for server-facilitator coordination
 */

import type { Request, Response } from 'express';
import type { NonceDatabase } from '../lib/nonce-database.js';

export interface StoreNonceContext {
  nonceDb: NonceDatabase;
}

/**
 * Store a nonce generated by the server for later settlement
 * This enables proper x402 protocol coordination
 */
export function storeNonceRoute(context: StoreNonceContext) {
  return async (req: Request, res: Response) => {
    const {
      nonce,
      amount,
      recipient,
      resourceId,
      resourceUrl,
      timestamp,
      expiry,
      splitPayment
    } = req.body;

    if (!nonce || !amount || !recipient || !resourceId) {
      return res.status(400).json({
        status: 'error',
        error: 'Missing required fields: nonce, amount, recipient, resourceId'
      });
    }

    try {
      // Store nonce with split payment data
      await context.nonceDb.storeNonce({
        nonce,
        clientPublicKey: '', // Will be set when payment is submitted
        amount,
        recipient,
        resourceId,
        resourceUrl: resourceUrl || resourceId,
        timestamp: timestamp || Date.now(),
        expiry: expiry || (Date.now() + 300000), // 5 minutes default
        splitPaymentData: splitPayment
      });

      console.log(`🔗 Nonce stored: ${nonce} for ${amount} lamports`);
      if (splitPayment?.enabled) {
        console.log(`   Split payment: ${splitPayment.recipients.length} recipients`);
      }

      res.json({
        status: 'success',
        nonce,
        expiry
      });

    } catch (error) {
      console.error('Failed to store nonce:', error);
      res.status(500).json({
        status: 'error',
        error: 'Failed to store nonce'
      });
    }
  };
}